services:
  postgres:
    image: postgres:16
    container_name: pg16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: demo
    ports: ["5433:5432"]
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d

  mysql:
    image: mysql:8.4
    container_name: mysql84
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: laba2
      MYSQL_USER: admin
      MYSQL_PASSWORD: wizford123456789
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports: ["3307:3306"]
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d